Pull in required header file(s).
Addressing
_build/src/github.com/canonical/go-dqlite/internal/bindings/server.go:11:10: fatal error: dqlite.h: No such file or directory
   11 | #include <dqlite.h>
      |          ^~~~~~~~~~
compilation terminated.

_build/src/github.com/canonical/go-dqlite/internal/bindings/server.go:12:10: fatal error: raft.h: No such file or directory
   12 | #include <raft.h>
      |          ^~~~~~~~
compilation terminated.

_build/src/github.com/canonical/go-dqlite/internal/bindings/server.go:13:10: fatal error: sqlite3.h: No such file or directory
   13 | #include <sqlite3.h>
      |          ^~~~~~~~~~~
compilation terminated.