Copr does not support plain http.
Addressing
curl: (1) Protocol "http" not supported or disabled in libcurl
error: Couldn't download http://www.sqlite.org/2020/sqlite-src-3310100.zip
Failed to execute command.